[blur-my-shell]
rounded-blur-found=false
settings-version=2

[blur-my-shell/appfolder]
brightness=0.59999999999999998
sigma=30

[blur-my-shell/coverflow-alt-tab]
pipeline='pipeline_default'

[blur-my-shell/dash-to-dock]
blur=true
brightness=0.59999999999999998
pipeline='pipeline_default_rounded'
sigma=30
static-blur=true
style-dash-to-dock=0

[blur-my-shell/lockscreen]
pipeline='pipeline_default'

[blur-my-shell/overview]
pipeline='pipeline_default'

[blur-my-shell/panel]
brightness=0.59999999999999998
pipeline='pipeline_default'
sigma=30

[blur-my-shell/screenshot]
pipeline='pipeline_default'

[blur-my-shell/window-list]
brightness=0.59999999999999998
sigma=30

[caffeine]
cli-toggle=false
indicator-position=-1
indicator-position-max=2
inhibit-apps=['qemu.desktop']
nightlight-control='never'
restore-state=false
screen-blank='never'
show-indicator='always'
show-notifications=true
show-timer=true
toggle-shortcut=['<Alt>c']
toggle-state=false

[dash-to-dock]
background-opacity=0.85999999999999999
custom-background-color=false
custom-theme-shrink=false
dash-max-icon-size=52
dock-position='BOTTOM'
height-fraction=0.90000000000000002
preferred-monitor=-2
preferred-monitor-by-connector='eDP-1'
running-indicator-style='DOTS'
transparency-mode='FIXED'

[system-monitor]
show-memory=true
